---
- hosts: all
  become: true
  gather_facts: false
  ansible_password: "ashu1234"
  tasks:

    - name: install docker 
      apt:
        name: docker 
        state: present
        update_cache: true

    - name: start docker
      systemd:
        name: docker
        state: started
    
    