---
- hosts: all
  become: true
  gather_facts: false
  
  tasks:

    - name: install docker 
      apt:
        name: docker.io
        state: latest
        update_cache: yes
        enabled: true

    - name: start docker
      systemd:
        name: docker
        state: restarted
    
    