---
- hosts: all
  become: true
  connection: ssh
  gather_facts: False

  tasks:
    - name: copy war file to node
      copy:
        src: /home/ubuntu/docker/*.war
        dest: /opt/
    - name: copy dockerfile
      copy:
        src: /home/ubuntu/docker/Dockerfile
        dest: /opt/

    - name: Building docker image
      shell: "cd /opt/"
      shell: "docker build -t yadavashu/test_img:$BUILD_ID ."

    - name: Run Docker container
      shell: "docker run -td --name test-cont -p 80:80 yadavashu/test_img:$BUILD_ID"
  
