---
- hosts: all
  become: true
  connection: ssh
  garther_facts: False
  tasks:
    - name: copy war file to node
      copy:
        src: /opt/docker/webapp.war
        dest: /opt/

    - name: Building docker image
      shell: "cd /opt/"
      shell: "docker build -t yadavashu/test_img:$BUILD_ID ."

    - name: Run Docker container
      shell: "docker run -td --name test-cont -p 80:80 yadavashu/test_img:$BUILD_ID"
  
