---
- hosts: all
  become: true
  connection: ssh
  gather_facts: False
  vars_files:
    - varsfile.yml
  tasks:
    - name: copy war file to node
      copy:
        src: /home/ubuntu/docker/mvnwebapp.war
        dest: /opt/
        force: yes
    - name: copy dockerfile
      copy:
        src: /home/ubuntu/docker/Dockerfile
        dest: /opt/
        force: yes

    - name: stop and remove running docker
      shell: docker stop test-cont; docker rm test-cont
      become: true
      ignore_errors: true
      
    - name: remove previous image
      shell: docker rmi -f yadavashu/{{ job_name }}:{{ item }}
      loop: "{{ version }}"
      become: true
      notify: building docker image
      ignore_errors: true

  handlers:
    - name: building docker image
      shell: docker build -t yadavashu/{{ job_name }}:{{ build_id }} /opt/.
      become: true
      notify: run_container

    - name: run_container
      shell: docker run -td --name test-cont -p 8080:8080 yadavashu/{{ job_name }}:{{ build_id }}
      become: true
