---
- hosts: all
  become: true
  connection: ssh
  gather_facts: False

  tasks:
    - name: copy war file to node
      copy:
        src: /home/ubuntu/docker/mvnwebapp.war
        dest: /opt/
        force: yes
    - name: copy dockerfile
      copy:
        src: /home/ubuntu/docker/Dockerfile
        dest: /opt/
        force: yes

    - name: Building docker image
      shell: docker rmi -f yadavashu/test_img; docker build -t yadavashu/test_img /opt/.
      become: true

    - name: Run Docker container
      shell: docker stop test-cont; docker rm test-cont; docker run -td --name test-cont -p 8080:8080 yadavashu/test_img
      become: true
